# fly.toml app configuration file generated for fso-phonebook-backend-ca on 2023-05-25T13:25:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fso-phonebook-backend-ca"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
