# fly.toml app configuration file generated for dawn-pine-5860 on 2023-05-23T15:13:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dawn-pine-5860"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
